#!/usr/bin/env python3

import sys
import webbrowser

# Check if URL was provided as a command-line argument
if len(sys.argv) < 2:
    print("Please provide a URL as a command-line argument.")
    sys.exit(1)


url = sys.argv[1] # Argument passed via terminal (domain name)

if 'https://' not in url:
    url = 'https://' + sys.argv[1]
if '.com' not in url:
    url = url + '.com'

webbrowser.open(url)



