#!/usr/bin/env python3

import os
import subprocess
import sys

import webbrowser
import validators

# Check if URL was provided as a command-line argument
if len(sys.argv) < 2:
    print("Please provide a URL as a command-line argument.")
    sys.exit(1)

url = sys.argv[1]  # Argument passed via terminal

# Validate the URL
if validators.url(url):  # URL should include http:// or https://
    webbrowser.open(url)
else:
    print("The provided URL is not valid. Please include 'http://' or 'https://'.")
